### ISSUE TITLE
Dimension array triggers an error

### ISSUE THREAD

**Issue by message** [sprity/sprity#2]
```js
{
	src: map,
	out: sourceSprite,
	name: "sprite",
	style: "_sprite.scss",
	cssPath: "/" + config.folders.images + "/",
	processor: "sass",
	"style-type": "scss",
	"style-indent-char": "tab",
	dimension: [
		{
			ratio: 1, dpi: 72
		},
		{
			ratio: 2, dpi: 192
		}
	]
}
```
leads to 
```
Unhandled rejection TypeError: Cannot read property 'width' of undefined
  at Object.validateRawBufferProperties [as validator] (/home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip/lib/util.js:53:14)
  at /home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:34:28
  at Array.forEach (native)
  at match (/home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:32:12)
  at /home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:55:30
  at Object.open (/home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip/lib/obtain.js:23:31)
  at /home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/index.js:68:10
  at scaleImage (/home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/index.js:67:10)
  at Object.module.exports.scale (/home/admin/www/app/node_modules/sprity/node_modules/sprity-lwip/index.js:100:12)
  at scaleSprite (/home/admin/www/app/node_modules/sprity/lib/sprite.js:64:17)
  at createSprite (/home/admin/www/app/node_modules/sprity/lib/sprite.js:80:13)
  at /home/admin/www/app/node_modules/sprity/lib/sprite.js:102:14
From previous event:
  at createOtherSprites (/home/admin/www/app/node_modules/sprity/lib/sprite.js:101:18)
  at /home/admin/www/app/node_modules/sprity/lib/sprite.js:117:45
From previous event:
  at DestroyableTransform._transform (/home/admin/www/app/node_modules/sprity/lib/sprite.js:115:10)
  at DestroyableTransform.Transform._read (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at /home/admin/www/app/node_modules/sprity/lib/layout.js:62:16
  at /home/admin/www/app/node_modules/lodash/index.js:3159:15
  at baseForOwn (/home/admin/www/app/node_modules/lodash/index.js:2089:14)
  at /home/admin/www/app/node_modules/lodash/index.js:3129:18
  at Function.<anonymous> (/home/admin/www/app/node_modules/lodash/index.js:3406:13)
  at DestroyableTransform._flush (/home/admin/www/app/node_modules/sprity/lib/layout.js:61:9)
  at DestroyableTransform.<anonymous> (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:117:20)
  at finishMaybe (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
  at endWritable (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
  at DestroyableTransform.Writable.end (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
  at DestroyableTransform.onend (/home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:117:20)
  at /home/admin/www/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:448:13)
```

However, single dimension array doesn't produce any errors
```js
dimension: [
	{
		ratio: 1, dpi: 72
	}
]
```

**Comment by aslansky** [comment]
Are you on version 1.0.2? Just asking because I thought I fixed that already.

**Comment by aslansky** [comment]
Never mind you were right. I will have a look into it as fast as possible.

**Comment by aslansky** [comment]
Should work with version 1.0.3
