### ISSUE TITLE
Example with error

### ISSUE THREAD

**Issue by GuiAlmeida** [sprity/sprity#32]
```javascript
[18:46:03] Starting 'sprites'...
[18:46:03] 'sprites' errored after 310 ms
[18:46:03] ReferenceError: gulpif is not defined
    at Gulp.<anonymous> (C:\Git\projetos\verdadeVida\gulpfile.js:61:9)
    at module.exports (C:\Git\projetos\verdadeVida\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Git\projetos\verdadeVida\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Git\projetos\verdadeVida\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Git\projetos\verdadeVida\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Guilherme\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

events.js:85
      throw er; // Unhandled 'error' event
            ^
LayoutError: No layouts created

```

**Comment by rayliao** [comment]
You should install `gulpif`:
`npm install gulpif`
