### ISSUE TITLE
prettydiff issue

### ISSUE THREAD

**Issue by retallicka** [sprity/sprity#42]
I get an error with the latest prettydiff, maybe some module naming changes?

`Error: Cannot find module 'prettydiff'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)`

If I use 1.15.17 everything works ok

**Comment by retallicka** [comment]
This appears to be a problem with prettydiff itself
