### ISSUE TITLE
Sprity can't be used after install: Error: Cannot find module 'prettydiff'

### ISSUE THREAD

**Issue by janmarek** [sprity/sprity#43]
I installed sprity via npm:

```
npm install --save sprity
```

Then I created file test.js where sprity is required:

```
var sprity = require('sprity');
```

When I tried to run it (`node test.js`) I got this error

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'prettydiff'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/janmarek/www/sprity/node_modules/sprity/lib/style.js:10:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/janmarek/www/sprity/node_modules/sprity/index.js:11:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by stephanedemotte** [comment]
same here

**Comment by stephanedemotte** [comment]
for quick fix : npm install prettydiff@1.16.4

**Comment by janmarek** [comment]
or pick another library (spritesmith in my case)
