### ISSUE TITLE
PluggableError: lwip not found

### ISSUE THREAD

**Issue by eseceve** [sprity/sprity#47]
I just install sprity with `npm i sprity` and then when I used it with gulp I have this error:

```
[10:50:58] Starting 'sprites'...
[10:50:59] 'sprites' errored after 1.39 s
[10:50:59] Error: PluggableError: lwip not found.
    at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/.../node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /.../node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/.../node_modules/gulp/node_modules/orchestra
```

Sprity: 1.0.8
Node: 4.2.4
NPM: 2.14.12

**Comment by ernestoalejo** [comment]
This catch: https://github.com/sprity/sprity/blob/master/lib/util/require.js#L21 eats all exceptions, even if they are not related to the import. Also it throws an unhelpful error.

Try to install `sprity-lwip` first (`npm install sprity-lwip`). If it's already installed maybe there is another problem. Import the module directly in your code to surface the real error:

``` js
var tmp = require('sprity-lwip');
```

In my case there was a mismatch in the GLIBC version (recompiling for the new GLIBC fixed the issue) and the underneath error was:

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /XXXXXX/node_modules/sprity-lwip/node_modules/lwip/build/Release/lwip_image.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /XXXXXX/node_modules/sprity-lwip/node_modules/lwip/lib/Image.js:3:22
    at Object.<anonymous> (/XXXXXX/node_modules/sprity-lwip/node_modules/lwip/lib/Image.js:16:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /XXXXXX/node_modules/sprity-lwip/node_modules/lwip/lib/ImagePrototypeInit.js:3:17
    at Object.<anonymous> (/XXXXXX/node_modules/sprity-lwip/node_modules/lwip/lib/ImagePrototypeInit.js:620:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/XXXXXX/node_modules/sprity-lwip/node_modules/lwip/index.js:1:63)
```

**Comment by eseceve** [comment]
It's a sprity-lwip error https://github.com/sprity/sprity-lwip/issues/6 =/

**Comment by ernestoalejo** [comment]
Anyway sprity could do a better work here, and throw a more helpful exception. Maybe one or several of these:
- Add the full package name (`sprity-lwip`).
- Mention its a NPM package: "not found" is too generic, I thought it was searching a binary called `lwip`.
- Detect non-require errors (like mine, which was a compilation one) and rethrow them directly.

**Comment by dreamyguy** [comment]
Just got into this problem today, hit a wall... collapsed into oblivion.

Sprity: 1.0.8
Node: 4.3.0
NPM: 2.14.12

:panda_face: :warning: Never say no to panda...

**Comment by dreamyguy** [comment]
The problem is with [lwip](https://github.com/EyalAr/lwip). I cloned their repo and ran `npm install`, but the installation did not complete. I haven't tried it with another version of node yet.

**Comment by ernestoalejo** [comment]
@dreamyguy What error does `npm install sprity-lwip` returns?

**Comment by dreamyguy** [comment]
@ernestoalejo the errors are:

Running `npm install` _within_ **sprity-lwip**

```
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/lwip_decoder.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Me/.nvm/versions/node/v4.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/Me/.nvm/versions/node/v4.3.0/bin/node" "/Users/Me/.nvm/versions/node/v4.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Me/Sites/opensource/sprity-lwip/node_modules/lwip
gyp ERR! node -v v4.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/Me/.nvm/versions/node/v4.3.0/bin/node" "/Users/Me/.nvm/versions/node/v4.3.0/bin/npm" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Me/Sites/opensource/sprity-lwip/npm-debug.log
```

Running `npm install` _within_ **lwip**

```
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/lwip_decoder.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Me/.nvm/versions/node/v4.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/Me/.nvm/versions/node/v4.3.0/bin/node" "/Users/Me/.nvm/versions/node/v4.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Me/Sites/opensource/lwip
gyp ERR! node -v v4.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/Me/.nvm/versions/node/v4.3.0/bin/node" "/Users/Me/.nvm/versions/node/v4.3.0/bin/npm" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Me/Sites/opensource/lwip/npm-debug.log
```

And for reference.. Running `npm install` _within_ **sprity**

```
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0
/
> lwip@0.0.8 install /Users/Me/Sites/opensource/sprity/node_modules/sprity-lwip/node_modules/lwip
> node-gyp rebuild

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/util.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
../src/decoder/buffer_worker.cpp:8:56: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wc++11-compat-deprecated-writable-strings]
    _height(0), _channels(0), _trans(false), _metadata("") {
                                                       ^
1 warning generated.
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/jpeg_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/png_decoder.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/gif_decoder.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemnobs.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jcomapi.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapimin.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdapistd.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatadst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdatasrc.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcoefct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdcolor.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jddctmgr.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdhuff.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdinput.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmainct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmarker.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmaster.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdpostct.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdsample.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jerror.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctflt.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctfst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jfdctint.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctflt.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctfst.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jidctint.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jutils.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jmemmgr.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdarith.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jdmerge.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jaricom.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant1.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/jpeg/jquant2.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/png.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngset.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngget.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngrutil.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngtrans.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngread.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngwrite.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngrio.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngrtran.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngmem.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngerror.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/png/pngpread.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/adler32.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/crc32.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/gzlib.o
../src/lib/zlib/gzlib.c:256:24: warning: implicit declaration of function 'lseek' is invalid in C99 [-Wimplicit-function-declaration]
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^
../src/lib/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
1 warning generated.
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/gzread.o
../src/lib/zlib/gzread.c:30:15: warning: implicit declaration of function 'read' is invalid in C99 [-Wimplicit-function-declaration]
        ret = read(state->fd, buf + *have, len - *have);
              ^
../src/lib/zlib/gzread.c:591:11: warning: implicit declaration of function 'close' is invalid in C99 [-Wimplicit-function-declaration]
    ret = close(state->fd);
          ^
2 warnings generated.
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/infback.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/inflate.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/inftrees.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/inffast.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/uncompr.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/zutil.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/zlib/trees.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/gif/dgif_lib.o
../src/lib/gif/dgif_lib.c:379:23: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
        for (i = 0; i < GifFile->Image.ColorMap->ColorCount; i++) {
                    ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/lwip_decoder/src/lib/gif/gif_err.o
  CC(target) Release/obj.target/lwip_decoder/src/lib/gif/gifalloc.o
  SOLINK_MODULE(target) Release/lwip_decoder.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/lwip_decoder.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Me/.nvm/versions/node/v4.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/Me/.nvm/versions/node/v4.3.0/bin/node" "/Users/Me/.nvm/versions/node/v4.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Me/Sites/opensource/sprity/node_modules/sprity-lwip/node_modules/lwip
gyp ERR! node -v v4.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing sprity-lwip@1.0.6
```

**Comment by ernestoalejo** [comment]
@dreamyguy See if you have the requirements installed:
https://github.com/nodejs/node-gyp#installation

Also this is the issue you are probably seeing:
https://github.com/EyalAr/lwip/issues/220

If nothing works, try on Node v0.12; perhaps lwip is not compatible yet with Node v4.

**Comment by dreamyguy** [comment]
@ernestoalejo Cheers, I'll have a look at it when I have time. Will report more when I know. :+1:

**Comment by adyballa** [comment]
I changed from sprity to sprity-lwip and I had to require it.
On another project I used sprity, got the same error and required also lwip.

**Comment by jonricaurte** [comment]
I noticed this worked fine in 0.10.40, but didn't work in 0.12.10. For some reason my Chrome kept crashing. I forced quit Chrome and tried reinstalling lwip and it installed correctly and did not get the error. @ernestoalejo thanks for the tips on the tmp. That helped debugging.

**Comment by babukrishna** [comment]
Unable to install. 

npm install sprity-lwip.

npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.

**Comment by karol-f** [comment]
I've got the same - **Error: PluggableError: lwip not found.**
NodeJs - v5.11.1
NPM - 3.8.6

Installed node-gyp, python, make, C/C++ compiler

` Error: PluggableError: lwip not found.
  at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
  at emitOne (events.js:95:20)
  at Gulp.emit (events.js:182:7)
  at Gulp.Orchestrator._emitTaskDone (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:264:8)
  at /var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:275:23
  at finish (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:36:10)
  at Gulp.Orchestrator._runTask (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:134:8)
  at /var/www/jenkins/workspace/_wp_update/theme/node_modules/gulp-sequence/index.js:66:12
  at apply (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:353:38)
  at tryRun (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:232:19)
  at runThunk (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:225:11)
  at next (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:323:33)
  at Gulp.successListener (/var/www/jenkins/workspace/_wp_update/theme/node_modules/gulp-sequence/index.js:45:11)
  at emitOne (events.js:95:20)
  at Gulp.emit (events.js:182:7)
  at Gulp.Orchestrator._emitTaskDone (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:264:8)
  at /var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:275:23
  at finish (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:60:3)
  at Gulp.Orchestrator._runTask (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:214:10)
  at /var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:279:18
  at finish (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:29:3)
  at apply (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:352:38)
  at tryRun (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:232:19)
  at callback (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:193:24)
  at next (/var/www/jenkins/workspace/_wp_update/theme/node_modules/thunks/thunks.js:322:31)
  at Gulp.successListener (/var/www/jenkins/workspace/_wp_update/theme/node_modules/gulp-sequence/index.js:45:11)
  at emitOne (events.js:95:20)
  at Gulp.emit (events.js:182:7)
  at Gulp.Orchestrator._emitTaskDone (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:264:8)
  at /var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/index.js:275:23
  at finish (/var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:21:8)
  at /var/www/jenkins/workspace/_wp_update/theme/node_modules/orchestrator/lib/runTask.js:52:4
  at f (/var/www/jenkins/workspace/_wp_update/theme/node_modules/once/once.js:17:25)
  at DestroyableTransform.onend (/var/www/jenkins/workspace/_wp_update/theme/node_modules/end-of-stream/index.js:31:18)
  at emitNone (events.js:85:20)
  at DestroyableTransform.emit (events.js:179:7)
  at /var/www/jenkins/workspace/_wp_update/theme/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by hy20090501** [comment]
https://github.com/nodejs/node-gyp#installation

**Comment by krukid** [comment]
I'm also unable to use `sprity`. I've installed the `npm i sprity-cli` library, but running `./node_modules/.bin/sprity create ./dist/sprites ./src/sprites ...` fails with:

> [sprity] lwip not found.
> [sprity] Install the image processing engine with `npm install <engine-name> -g`

I then started up an interactive node instance and tried to require `lwip` manually and discovered that it fails to load:
`./node_modules/sprity-cli/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip# node`

> > require('.')
> > Error: Cannot find module '../build/Release/lwip_image'
> >     at Function.Module._resolveFilename (module.js:325:15)
> >     at Function.Module._load (module.js:276:25)
> >     at Module.require (module.js:353:17)
> >     at require (internal/module.js:12:17)
> >     at /usr/src/app/node_modules/sprity-cli/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip/lib/Image.js:3:22
> >     at Object.<anonymous> (/usr/src/app/node_modules/sprity-cli/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip/lib/Image.js:16:3)
> >     at Module._compile (module.js:409:26)
> >     at Object.Module._extensions..js (module.js:416:10)
> >     at Module.load (module.js:343:32)
> >     at Function.Module._load (module.js:300:12)

I then followed the advice of @hy20090501 (as I understood it) and rebuilt `lwip` in-place:
`./node_modules/sprity-cli/node_modules/sprity/node_modules/sprity-lwip/node_modules/lwip# npm i node-gyp -g && node-gyp configure && node-gyp build && node`

> > require('.')
> > { open: [Function: open], create: [Function: create] }

Now `./node_modules/.bin/sprity create ...` runs correctly:

> [sprity] Sprite created in /usr/src/dev/dist/sprites

This is bad, however. Any plans to fix? (`sprity-cli@1.0.1`)

---

> # node -v
> v4.4.3
> # npm -v
> 2.15.1
> # cat /etc/issue
> Debian GNU/Linux 8 \n \l

---

**Update**: ended up using `webpack-spritesmith` for my project, which does the job, even though requires some tricky setup

**Comment by rickdoesburg** [comment]
I'm having this issue. Probably linked to this? https://stackoverflow.com/questions/32707229/getting-errors-while-doing-npm-in-my-project

Alright edit:
How I fixed it:
- Installed nvm, installed node 0.12.7
- nvm use 0.12.7
- npm install lwip
- npm install sprity
- npm install sprity-sass

**Comment by shehi** [comment]
It's funny how people ask to change Node version, instead of updating their packages. How can a serious project (I don't mean this package, but our - users' - projects) play with the version of platform so easily, is beyond me. If I am locked to, let's say Node v6, I am dead locked. Please guys, don't ask this or that version of Node, instead update your works. We won't have a progress if we are locked to an archaic version of it.

**Comment by justforuse** [comment]
Maybe you can try spritesmith, I tried it and it has no error, https://github.com/Ensighten/spritesmith

**Comment by Shuunen** [comment]
Even if I agree with you @shehi, thanks @rickdoesburg for the temporary workaround

**Comment by ghost** [comment]
@rickdoesburg `nvm use 5`also works fine... :) Thx again for the workaround :)

**Comment by lmj0011** [comment]
it was such a pain trying to work around this with the most recent node version ( node 8 in my case), but I eventually did what @rickdoesburg did, somewhat. https://github.com/sprity/sprity/issues/47#issuecomment-239791099


How I worked around it:

- Installed [nvm](https://github.com/creationix/nvm)
- `nvm install 5.12.0`
- `nvm use 5.12.0`
- `rm -fr ./node_modules`
- `npm install && npm install --save sprity@1.0.8`

notes: 

if your node scripts contain some exotic esnext features with no transpilation done to them beforehand, then you're going to have a bad time with this work around. check https://node.green/ first

I never had a reason to use `nvm` until now. Seems like a handy tool for mess like this.

I agree with @shehi https://github.com/sprity/sprity/issues/47#issuecomment-254444325

<hr>

I did not test this, but it may be possible to skip the whole nvm dance by using `sprity` the programmatic way https://github.com/sprity/sprity#programatic-usage and swapping the defualt engine to `sprity-gm` https://github.com/sprity/sprity#options

**Comment by renestalder** [comment]
The only working solution I found is to set the node version to 5.12.0. Absolutely nothing wrong with @shehi's statement, but I can't make it working by updating my dependencies. It doesn't seem to fix the error, so I assume this has to be fixed deeper down the dependency tree.
