### ISSUE TITLE
Unknown arguments configuration

### ISSUE THREAD

**Issue by koh-osug** [sprity/sprity#56]
I'm running this on node v4.4.0 and get the attached error. I try to store several country flags as one sprite. Several days ago it was still working. I tried to revert node to a version 0.10.x and v0.12.x but it didn't help. Maybe some other package was automatically updated, but I'm not aware of which one it is.

```
Options: out="", name="sprite", style="../../../../css/sprite.css", dimension=[{"ratio":1,"dpi":72}], engine="lwip", cssPath="/static/img/icons/flags_iso/16/", format="png", processor="css", orientation="vertical", margin=4, prefix="country-icon", background="#FFFFFF", sort, split=false, opacity=0, style-indent-char="space", style-indent-size=2, logger={}
Fatal error: Unknown arguments configuration,[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

**Comment by joshblum** [comment]
+1

**Comment by jrbotros** [comment]
+1

**Comment by meredithblumenstock** [comment]
+1

**Comment by nbanta** [comment]
+1

**Comment by ztec** [comment]
I have the same error :

```
#node -v
v4.2.1
```

```
/app/site/backoffice/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:80
throw Error(errs);
^

Error: Unknown arguments configuration,[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
at Error (native)
at /app/site/backoffice/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:80:27
at Object.create (/app/site/backoffice/node_modules/lwip/lib/obtain.js:66:33)
at renderSprite (/app/site/backoffice/node_modules/sprity/lib/sprite.js:47:17)
at createSprite (/app/site/backoffice/node_modules/sprity/lib/sprite.js:81:13)
at DestroyableTransform._transform (/app/site/backoffice/node_modules/sprity/lib/sprite.js:124:9)
at DestroyableTransform.Transform._read (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
at DestroyableTransform.Transform._write (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
at doWrite (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
at writeOrBuffer (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
at DestroyableTransform.Writable.write (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
at write (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
at flow (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
at DestroyableTransform.pipeOnReadable (/app/site/backoffice/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
at emitNone (events.js:67:13)
at DestroyableTransform.emit (events.js:166:7)
```

**Comment by jferrie-urbandaddy** [comment]
+1

`$ node -v
v5.11.0`

**Comment by alcfeoh** [comment]
+1 - Node v4.4.5

Any known workaround for this? Which Node version would actually work?

**Comment by alcfeoh** [comment]
Running the npm installs suggested on this page actually fixed it for me: http://stackoverflow.com/questions/33500066/sprity-gulp-spriting-image-scss-generator-various-errors-when-run-task

**Comment by koh-osug** [comment]
I have analyzed this a bit. The LWIP which is used behind seems to receive invalid input. LWIP accepts input conforming to the decree syntax:

``` json
[
[
  {"__id":0,"name":"width","type":"p-number"},
  {"__id":1,"name":"height","type":"p-number"},
  {"__id":3,"name":"callback","type":"function"}
],
[
  {"__id":0,"name":"width","type":"p-number"},
  {"__id":1,"name":"height","type":"p-number"},
  {"__id":2,"name":"color","type":"color"},
  {"__id":3,"name":"callback","type":"function"}
]
]
```

But decree used in the `create` function for `lwip/lib/obtain.js` is receiving non matching arguments, several of the following form assembled in `renderSprite` in `sprite.js`:

``` json
{
"height":16,
"width":16,
"x":0,
"y":0,
"type":"png",
"offset":4,
"contents":{
"type":"Buffer",
"data":[
137,
80,
78,
71,
13,
10,
...
]
},
"path":"C:\\Users\\foobar\\Documents\\Projects\\test\\flags_iso\\16\\ke.png"
}
```

**Comment by koh-osug** [comment]
I have switched to http://1and1.github.io/spritepacker-maven-plugin/ as a fix. This works out of the box without all the problems related to this unresolved issue. Of course this works only in a Maven based build environment.

**Comment by allenz-crypto** [comment]
See https://github.com/sprity/sprity/pull/71
