### ISSUE TITLE
A subprocess (install lwip) fails

### ISSUE THREAD

**Issue by ryangun** [sprity/sprity#68]
sudo npm install sprity --save-dev
but a subprocess falis, I don't know what' wrong.

``` bash
> lwip@0.0.8 install /Users/ganzhonghuan/ryangun/www/gulp-demo/node_modules/lwip
> node-gyp rebuild

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ganzhonghuan/.nvm/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/ganzhonghuan/.nvm/versions/node/v6.3.0/bin/node" "/Users/ganzhonghuan/.nvm/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ganzhonghuan/ryangun/www/gulp-demo/node_modules/lwip
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:lwip@0.0.8 lwip@0.0.8 install: `node-gyp rebuild`
npm WARN install:lwip@0.0.8 Exit status 1
```

**Comment by z-ZYS-s** [comment]
The package `lwip` actually has been released to support node 6. See https://github.com/EyalAr/lwip/releases/tag/v0.0.9. But sprity still use old version.

**Comment by z-ZYS-s** [comment]
> Latest commit 0a39d86  on 18 Nov 2015 @aslansky aslansky Release 1.0.8

The author hasn't maintained this repo for 9 months. What's happened?

**Comment by CreativeZoller** [comment]
I have the same problem and this is the only issue why all my tasks are failing... What to do to fix this guys?

Or does anyone have other recommendations to replace this sprity package in my gulpfile?

**Comment by ghost** [comment]
The author has moved to Mars.

**Comment by tiaozi0912** [comment]
Install the package using node version <= 7.5.0 and then change the version to which you actually wanna use.

https://github.com/EyalAr/lwip/issues/297

**Comment by rdourado** [comment]
Are there any alternatives to this project? Resized images are being generated with dark edges here. I tried using Spritesmith, but it doesn't work at all. Is there a better option nowadays?

**Comment by picheli20** [comment]
If you are using it on `sprity-lwip` extension I've done this extension https://github.com/xcaliber-tech/sprity-jimp using `jimp` instead.
