### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by herlon214** [sprity/sprity#69]
Hi guys, I'm using w10. When I try to install the console show this:

``` js
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\dev\php\sejapremium\front\node_modules\lwip
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:lwip@0.0.8 lwip@0.0.8 install: `node-gyp rebuild`
npm WARN install:lwip@0.0.8 Exit status 1
SejaPremium@0.1.0 F:\dev\php\sejapremium\front
`-- (empty)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN SejaPremium@0.1.0 No description
npm WARN SejaPremium@0.1.0 No repository field.
npm WARN SejaPremium@0.1.0 No license field.
npm ERR! code 1

```

**Comment by ghost** [comment]
Same issue on os x

**Comment by procrastagonist** [comment]
I had same problem, try to install latest version of NPM. Command line: 

> npm i npm@latest -g

And reinstall **node-gyp** (global) and **lwip** (in local directory). It works for me

**Comment by baijunjie** [comment]
Same issue on osx 10.10.5

``` js
> canvas@1.1.6 install /Users/baijunjie/Documents/sprite/node_modules/canvassmith/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:342:68: error: too many arguments to function call, expected at
      most 2, have 4
    return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
           ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:4832:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:397:32: warning: 'CompileUnbound' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::CompileUnbound(
                               ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:1334:45: note: 
      'CompileUnbound' has been explicitly marked deprecated here
                       Local<UnboundScript> CompileUnbound(
                                            ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:406:32: warning: 'CompileUnbound' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::CompileUnbound(
                               ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:1334:45: note: 
      'CompileUnbound' has been explicitly marked deprecated here
                       Local<UnboundScript> CompileUnbound(
                                            ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:412:31: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                              ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:4007:56: note: 'New' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:424:3: error: redefinition of 'NanNew'
  NanNew<v8::StringObject, v8::Handle<v8::String> >(
  ^
../../nan/nan.h:417:3: note: previous definition is here
  NanNew<v8::StringObject, v8::Local<v8::String> >(
  ^
../../nan/nan.h:442:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:436:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:454:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:448:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:462:42: warning: 'ToUint32' is deprecated
      [-Wdeprecated-declarations]
        v8::Isolate::GetCurrent(), val)->ToUint32();
                                         ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:8196:22: note: 'ToUint32' has
      been explicitly marked deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:468:42: warning: 'ToUint32' is deprecated
      [-Wdeprecated-declarations]
        v8::Isolate::GetCurrent(), val)->ToUint32();
                                         ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:8196:22: note: 'ToUint32' has
      been explicitly marked deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:473:60: warning: 'ToInt32' is deprecated
      [-Wdeprecated-declarations]
    return v8::Int32::New(v8::Isolate::GetCurrent(), val)->ToInt32();
                                                           ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:8202:21: note: 'ToInt32' has
      been explicitly marked deprecated here
Local<Int32> Value::ToInt32() const {
                    ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:478:60: warning: 'ToInt32' is deprecated
      [-Wdeprecated-declarations]
    return v8::Int32::New(v8::Isolate::GetCurrent(), val)->ToInt32();
                                                           ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:8202:21: note: 'ToInt32' has
      been explicitly marked deprecated here
Local<Int32> Value::ToInt32() const {
                    ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:518:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(
                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:529:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(
                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:538:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), arg);
                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:544:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), arg);
                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:619:24: warning: 'NewExternal' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewExternal(v8::Isolate::GetCurrent(), resource);
                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2372:38: note: 'NewExternal'
      has been explicitly marked deprecated here
                       Local<String> NewExternal(
                                     ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in
      'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2241:19: note: 
      'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:622:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../../nan/nan.h:617:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../../nan/nan.h:624:24: warning: 'NewExternal' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewExternal(v8::Isolate::GetCurrent(), resource);
                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2372:38: note: 'NewExternal'
      has been explicitly marked deprecated here
                       Local<String> NewExternal(
                                     ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:637:27: error: redefinition of '_NanEscapeScopeHelper'
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:632:27: note: previous definition is here
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
                          ^
../../nan/nan.h:653:12: error: no matching function for call to
      '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:641:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:637:27: note: candidate template ignored: substitution failure
      [with T = v8::Primitive]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:658:12: error: no matching function for call to
      '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:641:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:637:27: note: candidate template ignored: substitution failure
      [with T = v8::Primitive]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:663:12: error: no matching function for call to
      '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:641:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:637:27: note: candidate template ignored: substitution failure
      [with T = v8::Boolean]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:668:12: error: no matching function for call to
      '_NanEscapeScopeHelper'
    return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:641:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEscapeScopeHelper(val))
                                          ^~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:637:27: note: candidate template ignored: substitution failure
      [with T = v8::Boolean]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:701:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:707:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:712:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:718:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:889:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:900:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/baijunjie/.node-gyp/6.9.1/include/node/node_buffer.h:46:40: note: 
      candidate function not viable: 2nd argument ('const char *') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/node_buffer.h:34:40: note: 
      candidate function not viable: no known conversion from 'const char *' to
      'v8::Local<v8::String>' for 2nd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/node_buffer.h:39:40: note: 
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:904:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:218:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
      v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:218:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
      for 1st argument
class Local {
      ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:222:13: note: candidate
      template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:911:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../../nan/nan.h:938:32: warning: 'Compile' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate* isolate, Source* source,
                    ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/Canvas.cc:7:
In file included from ../src/Canvas.h:22:
../../nan/nan.h:945:32: warning: 'Compile' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate* isolate, Source* source,
                    ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
15 warnings and 20 errors generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/baijunjie/Documents/sprite/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> lwip@0.0.8 install /Users/baijunjie/Documents/sprite/node_modules/sprity-lwip/node_modules/lwip
> node-gyp rebuild

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
In file included from ../../nan/nan.h:182:
../../nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated
      [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:3032:36: note: 
      'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated
      [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:4007:56: note: 'New' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated
      [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8.h:2751:22: note: 'SetAccessor'
      has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
/Users/baijunjie/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/baijunjie/Documents/sprite/node_modules/sprity-lwip/node_modules/lwip
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
sprite@1.0.0 /Users/baijunjie/Documents/sprite
└── sprity@1.0.8 

npm WARN sprite@1.0.0 No description
npm WARN sprite@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.1.6 (node_modules/canvassmith/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.1.6 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lwip@0.0.8 (node_modules/sprity-lwip/node_modules/lwip):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lwip@0.0.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

```

I'm going to collapse

**Comment by procrastagonist** [comment]
use https://github.com/twolfson/gulp.spritesmith,  it's working fine

**Comment by emerinohdz** [comment]
@mkarkachov thanks for the suggestion, works great!

**Comment by priyanshuchauhan** [comment]
Didn't worked for me using gulp to build css sprites 
```
var gulp = require("gulp");
var spritesmith = require("gulp.spritesmith");

function defaultTask() {
  // TODO: handle png etc
  var spriteData = gulp.src("fooFolder/*.jpg").pipe(
    spritesmith({
      imgName: "sprite.jpg",
      cssName: "outputSprite.css",
    })
  );
  return spriteData.pipe(gulp.dest("public/avatars/AF/"));
}

exports.default = defaultTask;

```
